apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - ../base/podinfo
  - ../base/capacitor
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
  - target:
      kind: OCIRepository
    patch: |
      - op: replace
        path: /metadata/namespace
        value: flux-system
